### ISSUE TITLE
 hi , I am having an issue with chart wrapper class in IE 8 , It working fine in IE 9.0 the error is" TypeError: Object doesn't support property or method 'createElementNS"

### ISSUE THREAD

**Issue by Mallareddy15** [Moykn/google-barchart-percent#4]
hi , I am having an issue with chart wrapper class in IE 8 , It working fine in IE 9.0 the error is" TypeError: Object doesn't support property or method 'createElementNS" 
Please help me.

**Comment by Moykn** [comment]
I have been busy but i will try to fix it to work with IE 8 as soon as possible. just need to learn how to work with vml.

Best regards, 
Denisson.

**Comment by Mallareddy15** [comment]
Hi,

Still it is not working in IE8 Please suggest me. I am very new to this.

**Comment by Moykn** [comment]
IE8 doesn't support svg it uses vml instead, im looking for a way to handle this, i will update you as soon as possible

Em 06/06/2013, às 06:37, Mallareddy15 notifications@github.com escreveu:
